// Code generated by mockery v2.46.2. DO NOT EDIT.

package catmock

import (
	context "context"

	model "github.com/slok/agebox/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// SecretPrinter is an autogenerated mock type for the SecretPrinter type
type SecretPrinter struct {
	mock.Mock
}

// PrintSecret provides a mock function with given fields: ctx, secret
func (_m *SecretPrinter) PrintSecret(ctx context.Context, secret *model.Secret) error {
	ret := _m.Called(ctx, secret)

	if len(ret) == 0 {
		panic("no return value specified for PrintSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Secret) error); ok {
		r0 = rf(ctx, secret)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSecretPrinter creates a new instance of SecretPrinter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretPrinter(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretPrinter {
	mock := &SecretPrinter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
