// Code generated by mockery (devel). DO NOT EDIT.

package catmock

import (
	context "context"

	model "github.com/slok/agebox/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// SecretPrinter is an autogenerated mock type for the SecretPrinter type
type SecretPrinter struct {
	mock.Mock
}

// PrintSecret provides a mock function with given fields: ctx, secret
func (_m *SecretPrinter) PrintSecret(ctx context.Context, secret *model.Secret) error {
	ret := _m.Called(ctx, secret)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Secret) error); ok {
		r0 = rf(ctx, secret)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
