// Code generated by mockery v2.5.1. DO NOT EDIT.

package encryptmock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/slok/agebox/internal/model"
)

// Encrypter is an autogenerated mock type for the Encrypter type
type Encrypter struct {
	mock.Mock
}

// Decrypt provides a mock function with given fields: ctx, secret, keys
func (_m *Encrypter) Decrypt(ctx context.Context, secret model.Secret, keys []model.PrivateKey) (*model.Secret, error) {
	ret := _m.Called(ctx, secret, keys)

	var r0 *model.Secret
	if rf, ok := ret.Get(0).(func(context.Context, model.Secret, []model.PrivateKey) *model.Secret); ok {
		r0 = rf(ctx, secret, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Secret)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Secret, []model.PrivateKey) error); ok {
		r1 = rf(ctx, secret, keys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Encrypt provides a mock function with given fields: ctx, secret, keys
func (_m *Encrypter) Encrypt(ctx context.Context, secret model.Secret, keys []model.PublicKey) (*model.Secret, error) {
	ret := _m.Called(ctx, secret, keys)

	var r0 *model.Secret
	if rf, ok := ret.Get(0).(func(context.Context, model.Secret, []model.PublicKey) *model.Secret); ok {
		r0 = rf(ctx, secret, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Secret)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.Secret, []model.PublicKey) error); ok {
		r1 = rf(ctx, secret, keys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
