// Code generated by mockery (devel). DO NOT EDIT.

package processmock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// IDProcessor is an autogenerated mock type for the IDProcessor type
type IDProcessor struct {
	mock.Mock
}

// ProcessID provides a mock function with given fields: ctx, secretID
func (_m *IDProcessor) ProcessID(ctx context.Context, secretID string) (string, error) {
	ret := _m.Called(ctx, secretID)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, secretID)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, secretID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
